#!/bin/bash
cd ~/feldman_led_matrix/scripts && sudo python main.py --led-rows=32 --led-chain=2  --led-brightness=30 --led-pwm-lsb-nanoseconds=80 --led-slowdown-gpio=2 --led-scan-mode=1 --margin_left=0 --font_main=18 --font_bold=18 --word=man
