#!/bin/bash
IP=10.200.200.209
IP=192.168.50.181

# If you have problems, probably $IP is not your raspberryPi's IP
scp -i ~/.ssh/id_rsa scripts/main.py pi@$IP:~/feldman_led_matrix/scripts/main.py;
scp -i ~/.ssh/id_rsa scripts/libs/config.py pi@$IP:~/feldman_led_matrix/scripts/libs/config.py;
# scp -r -i ~/.ssh/id_rsa scripts/libs/myfont pi@$IP:~/feldman_led_matrix/scripts/libs;
