#!/bin/sh
#FreeDNS updater script

echo "[*] Start Updater Script"
echo ""

HASHKEY="SzRuRFNHZ1FtcXZITnFJb2FoTkk6MTcyODQ1ODQ="
UPDATEURL="https://freedns.afraid.org/dynamic/update.php?$HASHKEY"
DOMAIN="amedeo.pi.ignorelist.com"

echo "UPDATEURL   = $UPDATEURL"
echo "DOMAIN      = $DOMAIN"

registered=$(nslookup $DOMAIN|tail -n2|grep A|sed s/[^0-9.]//g)
current=$(wget -q -O - http://checkip.dyndns.org|sed s/[^0-9.]//g)

echo "registered  = $registered"
echo "current     = $current"
echo ""

if [ "${current}" != "${registered}" ]; then
   wget -q --read-timeout=0.0 --waitretry=5 --tries=400 --output-document /dev/null $UPDATEURL
   if [ $? -eq 0 ]; then
     echo "$(date +"%b %_d %T") $(hostname) $0: IP address updated on freedns.afraid.org: new IP '${current}', old IP '${registered}'" >> ~/my_ip_logs2
   else
     echo "$(date +"%b %_d %T") $(hostname) $0: ERROR IP address could not be  updated on freedns.afraid.org: current IP '${current}', registered IP '${registered}'" >> ~/my_ip_logs2
   fi
fi
